"boomSeparation_Dist_mm"=	350
"tailChord_Length_mm"=	300
"boomOuter_Diameter_mm"=	18
"tailRudderChord_Length_mm"=	50
"tailElevatorChord_Length_mm"=	50
"tailRudder_Length_mm"=	100
"D1@Sketch5@tail_HorizBodyNaca0012_v1.3<1>.Part"=	"tailChord_Length_mm"
"D1@Sketch10@tail_HorizBodyNaca0012_v1.3<1>.Part"=	"tailElevatorChord_Length_mm"
"D2@aileron_root@tail_Elevator_v1.3<1>.Part"=	"D1@elevator_thickness@tail_HorizBodyNaca0012_v1.3<1>.Part" / 2
"D1@aileron_root@tail_Elevator_v1.3<1>.Part"=	"tailElevatorChord_Length_mm"
"D1@Sketch5@tail_HorizRibv_v1.3<2>.Part"=	"tailChord_Length_mm"
"D1@Sketch5@tail_VertRib_v1.3<4>.Part"=	"tailChord_Length_mm"
"D1@Sketch5@tail_VertBodyNaca0012_v1.3<1>.Part"=	"tailChord_Length_mm"
"Rudder@Sketch9@tail_VertBodyNaca0012_v1.3<1>.Part"=	"tailRudderChord_Length_mm"
"D2@aileron_root@tail_Rudder_v1.3<2>.Part"=	"D1@Sketch13@tail_VertBodyNaca0012_v1.3<1>.Part" / 2
"D1@aileron_root@tail_Rudder_v1.3<2>.Part"=	"tailRudderChord_Length_mm"
"D1@Boss-Extrude1@tail_Rudder_v1.3<2>.Part"=	"tailRudder_Length_mm"
"Width vert stab@Boss-Extrude1@tail_VertBodyNaca0012_v1.3<1>.Part"=	"tailRudder_Length_mm"
"D1@Boss-Extrude1@tail_Elevator_v1.3<1>.Part"=	"Horizontal stabiliser width@Boss-Extrude1@tail_HorizBodyNaca0012_v1.3<1>.Part"
"Horizontal stabiliser width@Boss-Extrude1@tail_HorizBodyNaca0012_v1.3<1>.Part"=	"boomSeparation_Dist_mm" - 2 *  ( 30 + "tailRib_Thickness_mm" ) 
"tailRib_Thickness_mm"=	1.5
"Thickness@Boss-Extrude1@tail_VertRib_v1.3<2>.Part"=	"tailRib_Thickness_mm"
"Thickness@Boss-Extrude1@tail_HorizRibv_v1.3<1>.Part"=	"tailRib_Thickness_mm"
